/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author juank
 */
public class Pagos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagos.class.getName());

    /**
     * Creates new form Pagos
     */
    public Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel5.setText("Pagos");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 120, 50));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel6.setText("Pagos seguros y verificados");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setText("Listar Metodos");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 33));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel8.setText("Metodos registrados.");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel9.setText("Lista tus tarjetas y");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 96, 224));
        jButton1.setText("Listar Metodos");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, java.awt.Color.blue, null));
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar Pago.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 250, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setText("Metodos de pago");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 33));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel12.setText("Metodos.");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel13.setText("Administra tus tarjetas y");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 96, 224));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jButton2.setText("Agregar Metodo");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, java.awt.Color.blue, null));
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarMet Pago.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 250, 180));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel17.setText("Editar Informacion");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 33));

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel18.setText("Facturacion.");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel19.setText("Actualiza tu direccion de");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(26, 96, 224));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EditarPago.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, java.awt.Color.blue, null));
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SActualizar Pago R.png"))); // NOI18N
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 250, 180));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel56.setText("Nuestro sistema de soporte esta disponible");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 20));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 19)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(26, 96, 224));
        jLabel46.setText("Soporte especializado");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        jLabel44.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel44.setText("Para ayudarte en cualquier momento.");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Soporte.png"))); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 100));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 410, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verificado.png"))); // NOI18N
        jLabel53.setText("jLabel43");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 100));

        jLabel57.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel57.setText("Utilizamos encriptacion de nivel bancario");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 20));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 19)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(26, 96, 224));
        jLabel47.setText("Tus pagos estan seguros");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        jLabel45.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel45.setText("Para proteger tu informacion.");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 20));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 410, -1));

        jTabbedPane1.addTab("Resumen", jPanel1);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(26, 96, 224));
        jLabel32.setText("3. Finalizar compra");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Finalizar Compra.png"))); // NOI18N
        jPanel16.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        jLabel38.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel38.setText("Usa un metodo de pago guardado ");
        jPanel16.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel39.setText("Selecciona el metodo de pago");
        jPanel16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel40.setText("Selecciona el plan");
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 290, 200));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setBackground(new java.awt.Color(26, 96, 224));
        jLabel43.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(26, 96, 224));
        jLabel43.setText("1. Datos del usuario");
        jPanel17.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 160, 30));

        jTextField5.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/circulo-de-usuarios.png"))); // NOI18N
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jLabel55.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel55.setText("Igrese su informacion para continuar con el pago");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel61.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel61.setText("Nombre Completo");
        jPanel17.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel62.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel62.setText("Telefono");
        jPanel17.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jTextField6.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel17.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, -1));

        jLabel63.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel63.setText("Correo electronico");
        jPanel17.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTextField7.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel17.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        jLabel64.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel64.setText("Documento");
        jPanel17.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jTextField8.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel17.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, -1));

        jPanel21.setBackground(new java.awt.Color(226, 238, 249));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(26, 96, 224));
        jLabel77.setText("Usaremos estos datos para enviarte la confirmacion del pago ");
        jPanel21.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I () . importante.png"))); // NOI18N
        jLabel78.setText("jLabel78");
        jPanel21.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel17.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 360, 40));

        jPanel14.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 360));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(26, 96, 224));
        jLabel41.setText("2. Direccion del servicio");
        jPanel18.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        jTextField3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel18.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ubicacion.png"))); // NOI18N
        jPanel18.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 50));

        jLabel65.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel65.setText("Ingresa la dirección donde se realizará el servicio técnico");
        jPanel18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel66.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel66.setText("Municipio");
        jPanel18.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel67.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel67.setText("Barrio");
        jPanel18.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 60, -1));

        jTextField4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel18.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, -1));

        jLabel76.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel76.setText("Direccion");
        jPanel18.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, -1));

        jTextField9.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jPanel18.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 140, -1));

        jPanel14.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 500, 150));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel68.setText("3. Finalizar compra");
        jPanel20.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        jTextField2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField2.setText("jTextField1");
        jPanel20.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, -1));

        jLabel69.setText("jLabel37");
        jPanel20.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel70.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel70.setText("Usa un metodo de pago guardado ");
        jPanel20.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel71.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel71.setText("Selecciona el metodo de pago");
        jPanel20.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel72.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel72.setText("Selecciona el plan");
        jPanel20.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel20.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 290, 220));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Comfirmar compra.png"))); // NOI18N
        jPanel19.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel74.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(26, 96, 224));
        jLabel74.setText("5. Aceptar");
        jPanel19.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jLabel75.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel75.setText("Finaliza tu compra");
        jPanel19.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jCheckBox1.setText("Acepto");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel19.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WWWWWWWWWWWWWWW.png"))); // NOI18N
        jButton4.setText("COMPRAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        jLabel79.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(26, 96, 224));
        jLabel79.setText("Terminos y condiciones");
        jPanel19.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        jPanel14.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 240, 130));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(26, 96, 224));
        jLabel80.setText("4. Resumen de compra");
        jPanel22.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 180, 30));

        jLabel81.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel81.setText("Revisa los detalles de tu compra");
        jPanel22.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resumen compra.png"))); // NOI18N
        jPanel22.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 3, -1, 40));

        jLabel83.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel83.setText("Plan seleccionado :");
        jPanel22.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 60, 120, -1));

        jLabel84.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel84.setText("Metodo de pago :");
        jPanel22.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        jLabel85.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel85.setText("Total a pagar :");
        jPanel22.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));
        jPanel22.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 10));

        jLabel86.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel86.setText("$150K");
        jPanel22.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, 30));

        jLabel87.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        jLabel87.setText("/COP");
        jPanel22.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, 30));

        jLabel88.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel88.setText("Plan Basico");
        jPanel22.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel89.setText("NEQUI");
        jPanel22.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, -1));

        jLabel95.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel95.setText("Tecnico seleccionado :");
        jPanel22.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel96.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel96.setText("Rodolfo");
        jPanel22.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jPanel14.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 290, 150));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(26, 96, 224))); // NOI18N
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel90.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel90.setText("Transacciones seguras");
        jPanel23.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WWWWWWWWWWWWWWW.png"))); // NOI18N
        jPanel23.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel14.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 380, 40));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TTTTTTTTTTTTTTTTTTTT.png"))); // NOI18N
        jPanel24.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel93.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel93.setText("Proceso Rapido");
        jPanel24.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        jPanel14.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 290, 40));

        jTabbedPane1.addTab("Pagar", jPanel14);

        jPanel10.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 510));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_redisenado.png"))); // NOI18N
        jLabel3.setText("MENU");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 110, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/airservice_resized.png"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_usuario_60.png"))); // NOI18N
        jLabel16.setText(" USUARIO");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 130, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/result_image.png"))); // NOI18N
        jLabel4.setText("SERVICIOS");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 140, 60));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagos seguros.png"))); // NOI18N
        jLabel2.setText("PAGOS");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 110, 60));

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pagos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
