/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.Tarjeta;
import javax.swing.JOptionPane;

/**
 *
 * @author juank
 */
public class VentanaEditarMetodo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEditarMetodo.class.getName());

    /**
     * Creates new form VentanaEditarMetodo
     */
    public VentanaEditarMetodo() {
        initComponents();
        setSize(411 , 350);
        setResizable(false);
        setTitle("Agregar Metodo");
        this.setLocationRelativeTo(this);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNumTarjeta2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtCodigoS2 = new javax.swing.JTextField();
        TxtFechaV2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNombreTitular2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Editar Metodo de pago");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setText("Numero de tarjeta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(TxtNumTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        jLabel4.setText("Codigo de segurdad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        jPanel1.add(TxtCodigoS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, -1));
        jPanel1.add(TxtFechaV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, -1));

        jLabel5.setText("Fecha de vencimineto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel3.setText("Nombre del titular de la tarjeta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(TxtNombreTitular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String numeroTarjetaIngresado = TxtNumTarjeta2.getText().trim();
    String titular = TxtNombreTitular2.getText().trim();
    String vencimiento = TxtFechaV2.getText().trim();
    String Codigo = TxtCodigoS2.getText().trim();
    
    if(numeroTarjetaIngresado.isEmpty() || titular.isEmpty() || vencimiento.isEmpty()|| Codigo.isEmpty()){
        JOptionPane.showConfirmDialog(this, "Algun campo esta vacio." , "Campo Vacio" , JOptionPane.WARNING_MESSAGE);
        return;
    }
    boolean tarjetaEncontrada = false;
    for(int i = 0; i< Pagos.ListaTarjeta.size(); i++){
        Tarjeta  t = Pagos.ListaTarjeta.get(i);
        if(t.getNumeroTarjeta().equals(numeroTarjetaIngresado)){
            t.setNombreTitular(titular);
            t.setFechaVencimiento(vencimiento);
            t.setCodigoS(Codigo);
            
            tarjetaEncontrada = true ;
        }
    }
    
    if(tarjetaEncontrada){
        Pagos.actualizarComboxMetodos();
        JOptionPane.showMessageDialog(this, "Metodo actualizado con exito." , "Exito", JOptionPane.OK_OPTION);
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(this, "El numero de tarjeta ingresado no coincide con algun metodo registrado." 
                ,"Eror" , JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaEditarMetodo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField TxtCodigoS2;
    public static javax.swing.JTextField TxtFechaV2;
    public static javax.swing.JTextField TxtNombreTitular2;
    public static javax.swing.JTextField TxtNumTarjeta2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
