/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.Tarjeta;
import javax.swing.JOptionPane;

/**
 *
 * @author juank
 */
public class VentanaAgregarMetodo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAgregarMetodo.class.getName());

    /**
     * Creates new form VentanaAgregarMetodo
     */
    public VentanaAgregarMetodo() {
        initComponents();
        setSize(411 , 350);
        setResizable(false);
        setTitle("Agregar Metodo");
        this.setLocationRelativeTo(this);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNumTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNombreTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtCodigoS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFechaV = new javax.swing.JTextField();
        BtonAgregarMetodo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agregar Metodo de pago");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setText("Numero de tarjeta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(TxtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        jLabel3.setText("Nombre del titular de la tarjeta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(TxtNombreTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, -1));

        jLabel4.setText("Codigo de segurdad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        jPanel1.add(TxtCodigoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, -1));

        jLabel5.setText("Fecha de vencimineto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));
        jPanel1.add(TxtFechaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, -1));

        BtonAgregarMetodo1.setText("Agregar Metodo");
        BtonAgregarMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonAgregarMetodo1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtonAgregarMetodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtonAgregarMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonAgregarMetodo1ActionPerformed
        String NombreTitular = TxtNombreTitular.getText().trim();
        String FechaVencimiento = TxtFechaV.getText().trim();
        String NumeroTarjeta = TxtNumTarjeta.getText().trim();
        String CodigoS = TxtCodigoS.getText().trim();
        
        if(NombreTitular.isEmpty() || FechaVencimiento.isEmpty() || NumeroTarjeta.isEmpty() || CodigoS.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Algun Campo esta vacio.",
                    "Campos incompletos " , JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(NumeroTarjeta.length() < 16){
            JOptionPane.showMessageDialog(this, "El numero de tarjeta debe contener al menos 16 digitos.",
           "numero invalido" , JOptionPane.ERROR_MESSAGE );
            return;
        }
        if (CodigoS.length() < 3){
            JOptionPane.showMessageDialog(this, " EL codigo de seguridad (CVV) debe tener al menos 3-4 digitos.",
               "COdigo invalido" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        Tarjeta tar = new Tarjeta(NombreTitular, FechaVencimiento, NumeroTarjeta, CodigoS);
        Pagos.ListaTarjeta.add(tar);
        Pagos.actualizarComboxMetodos();
        
        JOptionPane.showMessageDialog(this, "Metodo registrado y verificado con exito...!" ,
                "Operacion exitosa " , JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
        
    }//GEN-LAST:event_BtonAgregarMetodo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaAgregarMetodo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtonAgregarMetodo1;
    public static javax.swing.JTextField TxtCodigoS;
    public static javax.swing.JTextField TxtFechaV;
    public static javax.swing.JTextField TxtNombreTitular;
    public static javax.swing.JTextField TxtNumTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
