
package Vistas;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author EUMAPE
 */
public class vista_admin extends javax.swing.JFrame {

    /**
     * Creates new form vista_admin
     */
    public vista_admin() {
        initComponents();
        fechaActual.setText(fecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        listarServicio = new javax.swing.JButton();
        agregarUsuarios = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        eliminarUsuarios = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        actualizarUsuarios = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        buscarUsuarios = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        actualizarTecnicos = new javax.swing.JButton();
        listarTecnicos = new javax.swing.JButton();
        eliminarTecnicos = new javax.swing.JButton();
        agregarTecnicos = new javax.swing.JButton();
        buscarTecnicos = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        listarTecnicos1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        agregarServicios = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField16 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        fechaActual = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 41, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(243, 244, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido, Administrador");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 480, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Gestiona clientes, tecnicos y servicios.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jTabbedPane3.addTab("0", jPanel3);

        jPanel6.setBackground(new java.awt.Color(243, 244, 246));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Gestion Usuarios ");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setIconTextGap(10);
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        listarServicio.setBackground(new java.awt.Color(0, 102, 204));
        listarServicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listarServicio.setForeground(new java.awt.Color(255, 255, 255));
        listarServicio.setText("Listar Usuarios");
        listarServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        listarServicio.setBorderPainted(false);
        listarServicio.setContentAreaFilled(false);
        listarServicio.setOpaque(true);
        listarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarServicioActionPerformed(evt);
            }
        });
        jPanel6.add(listarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 205, 30));

        agregarUsuarios.setBackground(new java.awt.Color(0, 102, 204));
        agregarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        agregarUsuarios.setText("Agregar Usuarios");
        agregarUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(209, 213, 219), 1, true));
        agregarUsuarios.setBorderPainted(false);
        agregarUsuarios.setContentAreaFilled(false);
        agregarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarUsuarios.setIconTextGap(10);
        agregarUsuarios.setOpaque(true);
        agregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuariosActionPerformed(evt);
            }
        });
        jPanel6.add(agregarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 205, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil.png"))); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, -1));

        eliminarUsuarios.setBackground(new java.awt.Color(0, 102, 204));
        eliminarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        eliminarUsuarios.setText("Eliminar Usuarios");
        eliminarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        eliminarUsuarios.setBorderPainted(false);
        eliminarUsuarios.setContentAreaFilled(false);
        eliminarUsuarios.setOpaque(true);
        eliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuariosActionPerformed(evt);
            }
        });
        jPanel6.add(eliminarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 205, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/investigacion.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 50, -1));

        actualizarUsuarios.setBackground(new java.awt.Color(0, 102, 204));
        actualizarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        actualizarUsuarios.setText("Actualizar Usuarios");
        actualizarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        actualizarUsuarios.setBorderPainted(false);
        actualizarUsuarios.setContentAreaFilled(false);
        actualizarUsuarios.setOpaque(true);
        actualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUsuariosActionPerformed(evt);
            }
        });
        jPanel6.add(actualizarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 205, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre.png"))); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        buscarUsuarios.setBackground(new java.awt.Color(0, 102, 204));
        buscarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        buscarUsuarios.setText("Buscar Usuarios");
        buscarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        buscarUsuarios.setBorderPainted(false);
        buscarUsuarios.setContentAreaFilled(false);
        buscarUsuarios.setOpaque(true);
        buscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuariosActionPerformed(evt);
            }
        });
        jPanel6.add(buscarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 205, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 50, -1));

        jTabbedPane3.addTab("1", jPanel6);

        jPanel7.setBackground(new java.awt.Color(243, 244, 246));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gestion Tecnicos");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        actualizarTecnicos.setBackground(new java.awt.Color(0, 102, 204));
        actualizarTecnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizarTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        actualizarTecnicos.setText("Actualizar Tecnicos");
        actualizarTecnicos.setBorderPainted(false);
        actualizarTecnicos.setContentAreaFilled(false);
        actualizarTecnicos.setOpaque(true);
        actualizarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecnicosActionPerformed(evt);
            }
        });
        jPanel7.add(actualizarTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 205, -1));

        listarTecnicos.setBackground(new java.awt.Color(0, 102, 204));
        listarTecnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listarTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        listarTecnicos.setText("Asignar Servicio");
        listarTecnicos.setBorderPainted(false);
        listarTecnicos.setContentAreaFilled(false);
        listarTecnicos.setOpaque(true);
        listarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTecnicosActionPerformed(evt);
            }
        });
        jPanel7.add(listarTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 205, -1));

        eliminarTecnicos.setBackground(new java.awt.Color(254, 226, 226));
        eliminarTecnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminarTecnicos.setForeground(new java.awt.Color(153, 27, 27));
        eliminarTecnicos.setText("Eliminar Tecnicos");
        eliminarTecnicos.setBorderPainted(false);
        eliminarTecnicos.setContentAreaFilled(false);
        eliminarTecnicos.setOpaque(true);
        eliminarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTecnicosActionPerformed(evt);
            }
        });
        jPanel7.add(eliminarTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 205, -1));

        agregarTecnicos.setBackground(new java.awt.Color(0, 102, 204));
        agregarTecnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        agregarTecnicos.setText("Agregar Tecnicos");
        agregarTecnicos.setBorderPainted(false);
        agregarTecnicos.setContentAreaFilled(false);
        agregarTecnicos.setOpaque(true);
        agregarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTecnicosActionPerformed(evt);
            }
        });
        jPanel7.add(agregarTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 205, -1));

        buscarTecnicos.setBackground(new java.awt.Color(0, 102, 204));
        buscarTecnicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        buscarTecnicos.setText("Buscar Tecnicos");
        buscarTecnicos.setBorderPainted(false);
        buscarTecnicos.setContentAreaFilled(false);
        buscarTecnicos.setOpaque(true);
        buscarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTecnicosActionPerformed(evt);
            }
        });
        jPanel7.add(buscarTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 205, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (1).png"))); // NOI18N
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre.png"))); // NOI18N
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil.png"))); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/investigacion.png"))); // NOI18N
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        listarTecnicos1.setBackground(new java.awt.Color(0, 102, 204));
        listarTecnicos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listarTecnicos1.setForeground(new java.awt.Color(255, 255, 255));
        listarTecnicos1.setText("Listar Tecnicos");
        listarTecnicos1.setBorderPainted(false);
        listarTecnicos1.setContentAreaFilled(false);
        listarTecnicos1.setOpaque(true);
        listarTecnicos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTecnicos1ActionPerformed(evt);
            }
        });
        jPanel7.add(listarTecnicos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 205, -1));

        jButton7.setBackground(new java.awt.Color(0, 122, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Volver");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jTabbedPane3.addTab("2", jPanel7);

        jPanel8.setBackground(new java.awt.Color(243, 244, 246));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Gestion Servicios");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 102, 204));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Listar Servicios");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton11.setContentAreaFilled(false);
        jButton11.setOpaque(true);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 205, 30));

        agregarServicios.setBackground(new java.awt.Color(0, 102, 204));
        agregarServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarServicios.setForeground(new java.awt.Color(255, 255, 255));
        agregarServicios.setText("Agregar Servicios");
        agregarServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        agregarServicios.setContentAreaFilled(false);
        agregarServicios.setOpaque(true);
        agregarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarServiciosActionPerformed(evt);
            }
        });
        jPanel8.add(agregarServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 205, 30));

        jButton13.setBackground(new java.awt.Color(0, 102, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Eliminar Servicios");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton13.setContentAreaFilled(false);
        jButton13.setOpaque(true);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 205, 30));

        jButton14.setBackground(new java.awt.Color(0, 102, 204));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Actualizar Servicios");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton14.setContentAreaFilled(false);
        jButton14.setOpaque(true);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 205, 30));

        jButton15.setBackground(new java.awt.Color(0, 102, 204));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Buscar Servicios");
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton15.setContentAreaFilled(false);
        jButton15.setOpaque(true);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 205, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-carpeta.png"))); // NOI18N
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chequeo.png"))); // NOI18N
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 40, 40));

        jButton8.setBackground(new java.awt.Color(0, 122, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Volver");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(true);
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jTabbedPane3.addTab("3", jPanel8);

        jPanel12.setBackground(new java.awt.Color(243, 244, 246));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(55, 65, 81));
        jLabel31.setText("Nombre Completo: *");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextField1.setBackground(new java.awt.Color(75, 85, 99));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, 20));

        jLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(55, 65, 81));
        jLabel32.setText("N Documento: *");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jTextField2.setBackground(new java.awt.Color(75, 85, 99));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel13.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, -1));

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(55, 65, 81));
        jLabel33.setText("Telefono:*");
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(55, 65, 81));
        jLabel34.setText("Nombre Completo: *");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextField3.setBackground(new java.awt.Color(75, 85, 99));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 20));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(55, 65, 81));
        jLabel35.setText("Direccion: *");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jTextField4.setBackground(new java.awt.Color(75, 85, 99));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField4.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 20));

        jLabel36.setBackground(new java.awt.Color(204, 204, 204));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(55, 65, 81));
        jLabel36.setText("Tipo de documento:*");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PEP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel13.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel37.setBackground(new java.awt.Color(204, 204, 204));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(55, 65, 81));
        jLabel37.setText("Repetir contraseña:*");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jTextField5.setBackground(new java.awt.Color(75, 85, 99));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField5.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel13.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 160, -1));

        jLabel38.setBackground(new java.awt.Color(204, 204, 204));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(55, 65, 81));
        jLabel38.setText("Correo Electronico: *");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel13.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, -1));
        jPanel13.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(55, 65, 81));
        jLabel39.setText("Contraseña: *");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 122, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar usuario");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 120, 30));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 660, 280));
        jPanel12.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("REGISTRAR NUEVO USUARIO");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (1).png"))); // NOI18N
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 122, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jPanel12.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        jTabbedPane3.addTab("4", jPanel12);

        jPanel15.setBackground(new java.awt.Color(243, 244, 246));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setBackground(new java.awt.Color(75, 85, 99));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField6.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, 20));

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(55, 65, 81));
        jLabel41.setText("N Documento: *");
        jPanel17.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jTextField7.setBackground(new java.awt.Color(75, 85, 99));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField7.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel17.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 160, -1));

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(55, 65, 81));
        jLabel42.setText("Telefono:*");
        jPanel17.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel43.setBackground(new java.awt.Color(204, 204, 204));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(55, 65, 81));
        jLabel43.setText("Nombre Completo: *");
        jPanel17.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextField8.setBackground(new java.awt.Color(75, 85, 99));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField8.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 20));

        jLabel44.setBackground(new java.awt.Color(204, 204, 204));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(55, 65, 81));
        jLabel44.setText("Direccion: *");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jTextField9.setBackground(new java.awt.Color(75, 85, 99));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField9.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 20));

        jLabel45.setBackground(new java.awt.Color(204, 204, 204));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(55, 65, 81));
        jLabel45.setText("Tipo de documento:*");
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PEP" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel17.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jTextField10.setBackground(new java.awt.Color(75, 85, 99));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField10.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel17.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 160, -1));

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(55, 65, 81));
        jLabel47.setText("Correo Electronico: *");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 122, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Buscar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 120, 30));

        jTextField11.setBackground(new java.awt.Color(75, 85, 99));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField11.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 20));

        jLabel50.setBackground(new java.awt.Color(204, 204, 204));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(55, 65, 81));
        jLabel50.setText("N Documento: *");
        jPanel17.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 660, 270));

        jButton4.setBackground(new java.awt.Color(0, 122, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Volver");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jPanel15.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("BUSCAR USUARIO");
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 40));
        jPanel15.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 10));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/investigacion.png"))); // NOI18N
        jPanel15.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 40));

        jTabbedPane3.addTab("5", jPanel15);

        jPanel18.setBackground(new java.awt.Color(243, 244, 246));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField12.setBackground(new java.awt.Color(75, 85, 99));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField12.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, 20));

        jLabel51.setBackground(new java.awt.Color(204, 204, 204));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(55, 65, 81));
        jLabel51.setText("N Documento: *");
        jPanel19.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jTextField13.setBackground(new java.awt.Color(75, 85, 99));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField13.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel19.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 160, -1));

        jLabel52.setBackground(new java.awt.Color(204, 204, 204));
        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(55, 65, 81));
        jLabel52.setText("Telefono:*");
        jPanel19.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel53.setBackground(new java.awt.Color(204, 204, 204));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(55, 65, 81));
        jLabel53.setText("Nombre Completo: *");
        jPanel19.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextField14.setBackground(new java.awt.Color(75, 85, 99));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField14.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 20));

        jLabel54.setBackground(new java.awt.Color(204, 204, 204));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(55, 65, 81));
        jLabel54.setText("Direccion: *");
        jPanel19.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jTextField15.setBackground(new java.awt.Color(75, 85, 99));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField15.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 20));

        jLabel55.setBackground(new java.awt.Color(204, 204, 204));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(55, 65, 81));
        jLabel55.setText("Tipo de documento:*");
        jPanel19.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PEP" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel19.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jTextField16.setBackground(new java.awt.Color(75, 85, 99));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField16.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPanel19.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 160, -1));

        jLabel56.setBackground(new java.awt.Color(204, 204, 204));
        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(55, 65, 81));
        jLabel56.setText("Correo Electronico: *");
        jPanel19.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 122, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buscar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 120, 30));

        jTextField17.setBackground(new java.awt.Color(75, 85, 99));
        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jTextField17.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 20));

        jLabel57.setBackground(new java.awt.Color(204, 204, 204));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(55, 65, 81));
        jLabel57.setText("N Documento: *");
        jPanel19.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 660, 270));

        jButton6.setBackground(new java.awt.Color(0, 122, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Volver");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219)));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jPanel18.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(51, 51, 51));
        jLabel58.setText("ELIMINAR USUARIO");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 40));
        jPanel18.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 10));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 40));

        jTabbedPane3.addTab("6", jPanel18);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane3.addTab("7", jPanel16);

        jPanel4.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 780, 410));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("X");
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 30));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 780, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre-de-negocios (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Administrador");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("INICIO");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-28.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("USUARIOS");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-male-user-28.png"))); // NOI18N
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("TECNICOS");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/obrero (1).png"))); // NOI18N
        jPanel10.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("SERVICIOS");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.png"))); // NOI18N
        jPanel11.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 160, 40));

        fechaActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaActual.setForeground(new java.awt.Color(0, 0, 0));
        fechaActual.setText("DD/MM/YYYY");
        jPanel1.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horizontal-panel.jpg"))); // NOI18N
        jLabel40.setText("jLabel40");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1590, 1060));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved
        jPanel14.setBackground(new Color (204,0,0));
    }//GEN-LAST:event_jPanel14MouseMoved

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        jPanel14.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_jPanel14MouseExited

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void agregarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarServiciosActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void buscarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTecnicosActionPerformed

    private void agregarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarTecnicosActionPerformed

    private void eliminarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarTecnicosActionPerformed

    private void listarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarTecnicosActionPerformed

    private void actualizarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarTecnicosActionPerformed

    private void buscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsuariosActionPerformed

    private void actualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarUsuariosActionPerformed

    private void eliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarUsuariosActionPerformed

    private void agregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarUsuariosActionPerformed

    private void listarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarServicioActionPerformed

    }//GEN-LAST:event_listarServicioActionPerformed

    private void listarTecnicos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTecnicos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarTecnicos1ActionPerformed

    public static String fecha(){
        Date fecha = new Date();
            SimpleDateFormat formato =  new SimpleDateFormat("DD/MM/YYYY");
            return formato.format(fecha);
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTecnicos;
    private javax.swing.JButton actualizarUsuarios;
    private javax.swing.JButton agregarServicios;
    private javax.swing.JButton agregarTecnicos;
    private javax.swing.JButton agregarUsuarios;
    private javax.swing.JButton buscarTecnicos;
    private javax.swing.JButton buscarUsuarios;
    private javax.swing.JButton eliminarTecnicos;
    private javax.swing.JButton eliminarUsuarios;
    private javax.swing.JLabel fechaActual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton listarServicio;
    private javax.swing.JButton listarTecnicos;
    private javax.swing.JButton listarTecnicos1;
    // End of variables declaration//GEN-END:variables
}
